import type { Metadata } from 'next'
import './globals.css'
import { IconHome, IconMap, IconNewspaper, IconUser } from './components/Icons'
import Link from 'next/link'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const iconColor = 'rgb(167 139 250)'

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="zhCN" data-theme="light">
            <body className="flex flex-col">
                <main className="flex-1">{children}</main>
                <footer className="flex-none bg-base-200">
                    <div className="flex justify-around p-3">
                        <Link href="#">
                            <IconHome size={'2.5rem'} color={iconColor} />
                        </Link>
                        <Link href="#">
                            <IconNewspaper size={'2.5rem'} color={iconColor} />
                        </Link>
                        <Link href="#">
                            <IconMap size={'2.5rem'} color={iconColor} />
                        </Link>
                        <Link href="#">
                            <IconUser size={'2.5rem'} color={iconColor} />
                        </Link>
                    </div>
                </footer>
            </body>
        </html>
    )
}
